### ISSUE TITLE
Scheduled Downtime succeeded on script but not on Nagios

### ISSUE THREAD

**Issue by bernardoVale** [willemdh/naf_schedule_downtime#1]
@willemdh, check the output. I've put some "echos" inside the script for debugging propose.

can you help me?

./naf_schedule_downtime.sh --NagiosServer 10.200.0.113 --NagiosUser bernardo.vale --NagiosPassword eduarda1992 --NrdpToken flessak --Target Flessak-PRD --Service check_disk --Duration 120 --Comment teste
2015-09-11 16:17:04,093: Info: Schedule downtime initiated on target Flessak-PRD, service check_disk with duration 120.
2015-09-11 16:17:04,094: Info: Checking if Flessak-PRD is a hostgroup.
{ "format_version": 0, "result": { "query_time": 1441999024000, "cgi": "objectjson.cgi", "user": "bernardo.vale", "query": "hostgrouplist", "query_status": "beta", "program_start": 1441977131000, "last_data_update": 1441977131000, "type_code": 0, "type_text": "Success", "message": "" }, "data": { "selectors": { }, "hostgrouplist": [ "AB", "AEBEL", "Apetit", "BRISA", "Bompel", "CANTU", "CAVALCA", "CSD", "Cionc", "DZ", "Flessak", "Grupo Filadelfia", "HNSL", "Holhos", "INA", "LB2", "LB2 BPI", "LaMucca", "NOVA", "Nabhan", "Ninfa", "PBLOPES", "SIGACRED", "Specialite", "Supremacia", "linux-servers" ] } }
2015-09-11 16:17:04,234: Info: Target hostgroup check result = false
2015-09-11 16:17:04,236: Info: Checking if Flessak-PRD is a host...
{ "format_version": 0, "result": { "query_time": 1441999024000, "cgi": "objectjson.cgi", "user": "bernardo.vale", "query": "hostlist", "query_status": "beta", "program_start": 1441977131000, "last_data_update": 1441977131000, "type_code": 0, "type_text": "Success", "message": "" }, "data": { "selectors": { }, "hostlist": [ "10.200.0.2", "AB-Infasa", "AB-Matriz", "AB-Standby-INFASA", "AB-Standby-ORCL", "AEBEL-BENETTON", "AEBEL-Balancer", "AEBEL-CAMARO", "AEBEL-CAPTIVA", "AEBEL-COROLLA", "AEBEL-DODGE", "AEBEL-EVOQUE", "AEBEL-FLUENCE", "AEBEL-FOCUS", "AEBEL-FUSION", "AEBEL-JETTA", "AEBEL-OPENFIRE", "AEBEL-ORACLEMV", "AEBEL-ORACLEOLD", "AEBEL-ORAMV", "AEBEL-PASSAT", "AEBEL-SENTRA", "AEBEL-TEMPRA", "AEBEL-TIPO", "AEBEL-TUCSON", "AEBEL-VCENTER", "AEBEL-VEYRON", "AEBEL-WEBPRD", "Apetit-PRD", "BRISA-SERVIDOR", "Bompel-PRD", "CANTU-CPX01", "CANTU-CPX02", "CLS-SQL-01_AMIGAO01", "CLS-SQL-02_AMIGAO02", "CSD-DB-CORPORERM", "CSD-DB-GESTAO", "CSD-DC1P-SF-BDSQL-1", "CSD-SRV_SQL_03", "Cantu-RJU01", "Cantu-RJU02", "Cionc-PRD", "DZ-servermsiga", "DZ-srvad", "DZ-vmsrvdb", "DZ-vmsrvsep", "DZ-vmsrvtotvs", "Filadelfia-PRD", "Flessak-PRD", "Gearman-Server", "HNSL-PRD", "Holhos-PRD", "INA-DAVI", "INA-SEP", "INA-TRAJANO", "LB2 BPI", "LB2-LDAP", "LaMucca", "Moinho-PRD", "Moinho-Teste", "NOVA-HPUX", "NOVA-NFE", "NOVA-USINA", "Nabhan-DVPRD11", "Nabhan-TMPRD12", "Ninfa", "Ninfa-PRD", "PBLOPES-DOMINO", "PBLOPES-SAMETIME", "SIGACRED-RAC02", "Sigacred-RAC01", "Specialite-PRD", "Supremacia-PRD", "Vmware", "localhost", "lotus.lb2.com.br", "unifi.aebel.local" ] } }
2015-09-11 16:17:04,339: Info: Target host check result = true
2015-09-11 16:17:04,343: Info: Attempting to schedule downtime for service check_disk on host Flessak-PRD.
2015-09-11 16:17:04,374: Info: Schedule downtime succeeded for service check_disk on host Flessak-PRD

**Comment by willemdh** [comment]
Hey, Thank you for trying this addon. It's working for me, so it should be possible to get it working for you too. For debugging you can set the verbose in 1 the beginning of the script.
Can you please try to schedule the downtime of one host and set --Service to 'All' without hte single quotes?
Can you try to use the curl command with the variables from shell:
    curl --fail --silent --show-error "http://$NagiosServer/nrdp/?cmd=submitcmd&token=$NrdpToken&command=SCHEDULE_HOST_DOWNTIME;$Target;$Now;$End;1;0;300;$NagiosUser;$Comment"

echo this command and then copy the echo  and try executing it in your shell. Are you 100 % sure your nrdp token is correct?

Grtz

Willem

**Comment by bernardoVale** [comment]
@willemdh i've created a small bash to test with your recommendation. Nagios are responding that the call was OK but didn't scheduled downtime.  

    #!/bin/bash
    NagiosServer=10.200.0.113
    NrdpToken=Flessak
    Target=Flessak-PRD
    Now=`date +%s`
    Duration=7200
    End=$((Now + $Duration))
    NagiosUser=bernardo.vale
    curl --fail --silent --show-error "http://$NagiosServer/nrdp/?             cmd=submitcmd&token=$NrdpToken&command=SCHEDULE_HOST_DOWNTIME;$Target;$Now;$End;1;0;300;$NagiosUser;$Comment"
    date -d $@Now +"%Y-%m-%d %H:%M:%S"

The output:

     <?xml version="1.0" encoding="utf-8"?>
     <result>
      <status>0</status>
      <message>OK</message>
     </result>
2015-09-14 11:41:37
[root@LB2-NagiosXI ~]# date
Mon Sep 14 11:41:39 BRT 2015

**Comment by willemdh** [comment]
Hmm, as it doesn't work with this small Bash script you made I suggest we continue troubleshooting this on the Nagios forum? It should work.

**Comment by willemdh** [comment]
Hey Bernardo, As you suggested it works now, can I close this issue?

**Comment by bernardoVale** [comment]
Thanks for you help Willemdh. I'm closing it
